Server.Update.GitHub.Webhook.Enable: True
#Server.RateLimit.Enable: True
ProjectInfo.GitInfo.Enable: True
Public.domain: news.bugjump.net
Server.Version.By: hash
Refresher.Enable: true
Refresher.Precision: d
NewsHomepage.Debug: False
#NewsHomepage.Protocol: https